spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/users_security
    username: postgres
    password: 87654321
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: security
    open-in-view: false
security:
  jwt:
    secret: 73357638792F423F4528482B4D6251655468576D5A7133743677397A24432646
    access: 1
    refresh: 2
server:
  port: 8081