spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/users_security
    username: postgres
    password: 87654321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret-key: 9AA5DCAA036A417302A9FF0F6CE3F48265239A19B072129616E9C19364790186
    expiration: 86400000 # 1 day (24 hours)
server:
  port: 8081